## H2 Configuration
h2:
  console:
    enabled: true
    path: /console
    settings:
      trace: false

## DB Configuration
spring:
  datasource:
    url: jdbc:h2:mem:advertiser-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

## Configuring info endpoint
info:
  app:
    name: Advertiser-App
    description: CRUD Spring boot application
    version: 1.0.0-RELEASE 
  java-vendor: ${java.specification.vendor}

management:
  server:
    port: 8090